<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for block \Magento\Catalog\Block\Adminhtml\Detail\Edit\Tab\Alerts
 */
?>
<div id="alert_messages_block"><?php echo $block->getMessageHtml() ?></div>
<div>
    <h4 class="icon-head head-edit-form"><?php /* @escapeNotVerified */ echo __('Detail Alerts') ?></h4>
</div>
<div class="clear"></div>
<?php echo $block->getAccordionHtml() ?>
